CREATE TABLE JOGADOR (
  ID NUMBER(5),
  USERNAME VARCHAR(20) NOT NULL,
  GENERO CHAR(1),
  EMAIL VARCHAR(50),
  SENHA VARCHAR(50) NOT NULL,
  CONSTRAINT PK_JOGADOR PRIMARY KEY (ID),
  CONSTRAINT AK_JOGADOR_USER UNIQUE (USERNAME),
  CONSTRAINT AK_JOGADOR_EMAIL UNIQUE (EMAIL)
);

CREATE TABLE AMIZADE (
  IDJ1 NUMBER(5),
  IDJ2 NUMBER(5),
  DATA_DE_INICIO DATE,
  CONSTRAINT PK_AMIZADE PRIMARY KEY (IDJ1, IDJ2),
  CONSTRAINT CHK_AMIZADE CHECK (IDJ1 < IDJ2),
  CONSTRAINT FK_AMIZADE_IDJ1 FOREIGN KEY (IDJ1) REFERENCES JOGADOR (ID),
  CONSTRAINT FK_AMIZADE_IDJ2 FOREIGN KEY (IDJ2) REFERENCES JOGADOR (ID)
);

CREATE TABLE CONQUISTA (
  CODIGO NUMBER(5),  
  NOME VARCHAR(50) NOT NULL,
  DESCRICAO VARCHAR(200),
  CONSTRAINT PK_CONQUISTA PRIMARY KEY (CODIGO)
);

CREATE TABLE DESBLOQUEIA (
  IDJ NUMBER(5),
  CODIGO_C NUMBER(5),  
  DATA_DESB DATE,
  CONSTRAINT PK_DESBLOQUEIA PRIMARY KEY (IDJ, CODIGO_C),
  CONSTRAINT FK_DESBLOQUEIA_IDJ FOREIGN KEY (IDJ) REFERENCES JOGADOR (ID),
  CONSTRAINT FK_DESBLOQUEIA_CODIGO_C FOREIGN KEY (CODIGO_C) REFERENCES CONQUISTA (CODIGO)
);

CREATE TABLE SESSAO (
  IDJ NUMBER(5),
  INICIO TIMESTAMP,
  DURACAO NUMBER(4, 2),  
  TEMPO_ACUMULADO NUMBER(6, 2),  
  CONSTRAINT PK_SESSAO PRIMARY KEY (IDJ, INICIO),
  CONSTRAINT FK_SESSAO_IDJ FOREIGN KEY (IDJ) REFERENCES JOGADOR (ID)
);

CREATE TABLE SERVIDOR (
  ID NUMBER(5),  
  NOME VARCHAR(50) NOT NULL,
  TIPO BOOLEAN NOT NULL,  
  SENHA VARCHAR(50),
  CONSTRAINT PK_SERVIDOR PRIMARY KEY (ID)
);

CREATE TABLE PUNICAO (
  CODIGO NUMBER(5),  
  NOME VARCHAR(50) NOT NULL,
  DESCRICAO VARCHAR(200),
  DURACAO NUMBER(4),  
  CONSTRAINT PK_PUNICAO PRIMARY KEY (CODIGO)
);

CREATE TABLE ACESSO (
  IDJ NUMBER(5),
  IDS NUMBER(5),
  AUTORIDADE NUMBER(1),  
  ULTIMO_ACESSO TIMESTAMP,
  CONSTRAINT PK_ACESSO PRIMARY KEY (IDJ, IDS),
  CONSTRAINT FK_ACESSO_IDJ FOREIGN KEY (IDJ) REFERENCES JOGADOR (ID),
  CONSTRAINT FK_ACESSO_IDS FOREIGN KEY (IDS) REFERENCES SERVIDOR (ID)
);

CREATE TABLE PUNIDO (
  IDJ NUMBER(5),
  IDS NUMBER(5),
  CODIGO_P NUMBER(5), 
  DATA_P DATE,
  CONSTRAINT PK_PUNIDO PRIMARY KEY (IDJ, IDS, CODIGO_P, DATA_P),
  CONSTRAINT FK_PUNIDO_IDJ_IDS FOREIGN KEY (IDJ, IDS) REFERENCES ACESSO (IDJ, IDS),
  CONSTRAINT FK_PUNIDO_CODIGO_P FOREIGN KEY (CODIGO_P) REFERENCES PUNICAO (CODIGO)
);

CREATE TABLE MAPA (
  SEED CHAR(50), 
  CONSTRAINT PK_MAPA PRIMARY KEY (SEED)
);

CREATE TABLE MUNDO (
  IDS NUMBER(5),  
  INDICE NUMBER(5), 
  NOME VARCHAR(50) NOT NULL,
  SEED_M CHAR(50) NOT NULL,
  CONSTRAINT PK_MUNDO PRIMARY KEY (IDS, INDICE),
  CONSTRAINT FK_MUNDO_SEED_M FOREIGN KEY (SEED_M) REFERENCES MAPA (SEED)
);

CREATE TABLE ESTRUTURA (
  SEED_M CHAR(50),
  CODIGO NUMBER(5),
  X NUMBER(6, 2),
  Y NUMBER(6, 2),
  Z NUMBER(6, 2),
  CONSTRAINT PK_ESTRUTURA PRIMARY KEY (SEED_M, CODIGO),
  CONSTRAINT FK_ESTRUTURA_SEED_M FOREIGN KEY (SEED_M) REFERENCES MAPA (SEED)
);

CREATE TABLE ITEM (
  ID NUMBER(5),
  TIPO VARCHAR(50) NOT NULL,
  NOME VARCHAR(50) NOT NULL,
  DESCRICAO VARCHAR(200),
  CONSTRAINT PK_ITEM PRIMARY KEY (ID)
);

CREATE TABLE POSSUI (
  IDJ NUMBER(5),
  IDI NUMBER(5),
  IDSM NUMBER(5),  
  INDICE_M NUMBER(5),  
  CONSTRAINT PK_POSSUI PRIMARY KEY (IDJ, IDI, IDSM, INDICE_M),
  CONSTRAINT FK_POSSUI_IDJ FOREIGN KEY (IDJ) REFERENCES JOGADOR (ID),
  CONSTRAINT FK_POSSUI_IDI FOREIGN KEY (IDI) REFERENCES ITEM (ID),
  CONSTRAINT FK_POSSUI_IDSM_INDICE_M FOREIGN KEY (IDSM, INDICE_M) REFERENCES MUNDO (IDS, INDICE)
);

CREATE TABLE COMPOE (
  IDMP NUMBER(5),
  IDP NUMBER(5),
  QUANTIDADE NUMBER(2),  
  CONSTRAINT PK_COMPOE PRIMARY KEY (IDMP, IDP),
  CONSTRAINT CHK_QUANTIDADE_POSITVA CHECK (QUANTIDADE > 0),
  CONSTRAINT FK_COMPOE_IDMP FOREIGN KEY (IDMP) REFERENCES ITEM (ID),
  CONSTRAINT FK_COMPOE_IDP FOREIGN KEY (IDP) REFERENCES ITEM (ID)
);

CREATE TABLE BAU (
  CODIGO NUMBER(5),  
  RARIDADE VARCHAR(10) NOT NULL,
  CAPACIDADE NUMBER(3) NOT NULL,
  CONSTRAINT PK_BAU PRIMARY KEY (CODIGO),
  CONSTRAINT CHK_CAPACIDADE_POSITIVA CHECK (CAPACIDADE > 0)
);

CREATE TABLE GUARDA (
  IDI NUMBER(5),
  CODIGO_B NUMBER(5), 
  PROBABILIDADE NUMBER(3, 2) NOT NULL,
  CONSTRAINT PK_GUARDA PRIMARY KEY (IDI, CODIGO_B),
  CONSTRAINT CHK_PROBABILIDADE CHECK (PROBABILIDADE >= 0 AND PROBABILIDADE <= 1),
  CONSTRAINT FK_GUARDA_IDI FOREIGN KEY (IDI) REFERENCES ITEM (ID),
  CONSTRAINT FK_GUARDA_CODIGO_B FOREIGN KEY (CODIGO_B) REFERENCES BAU (CODIGO)
);

CREATE TABLE VILA (
  SEED_ME CHAR(50),
  CODIGO_E NUMBER(5),
  QUANTIDADE_CASAS NUMBER(3) NOT NULL,
  CODIGO_B NUMBER,
  CONSTRAINT PK_VILA PRIMARY KEY (SEED_ME, CODIGO_E),
  CONSTRAINT CHK_QUANTIDADE_CASAS CHECK (QUANTIDADE_CASAS > 0),
  CONSTRAINT FK_VILA_SEED_ME FOREIGN KEY (SEED_ME, CODIGO_E) REFERENCES ESTRUTURA (SEED_M, CODIGO),
  CONSTRAINT CODIGO_B FOREIGN KEY (CODIGO_B) REFERENCES BAU (CODIGO)
);

CREATE TABLE ALDEAO (
  SEED_MEV CHAR(50),
  CODIGO_EV NUMBER(2),
  PROFISSAO VARCHAR(20) NOT NULL,
  CONSTRAINT PK_ALDEAO PRIMARY KEY (SEED_MEV, CODIGO_EV),
  CONSTRAINT FK_ALDEAO_SEED_MEV FOREIGN KEY (SEED_MEV, CODIGO_EV) REFERENCES VILA (SEED_ME, CODIGO_E)
);

CREATE TABLE FORTALEZA (
  SEED_ME CHAR(50),
  CODIGO_E NUMBER(2),
  QUANTIDADE_DE_NIVEIS NUMBER(2) NOT NULL,
  CONSTRAINT PK_FORTALEZA PRIMARY KEY (SEED_ME, CODIGO_E),
  CONSTRAINT CHK_QUANTIDADE_DE_NIVEIS CHECK (QUANTIDADE_DE_NIVEIS > 0),
  CONSTRAINT FK_FORTALEZA_SEED_ME_CODIGO_E FOREIGN KEY (SEED_ME, CODIGO_E) REFERENCES ESTRUTURA (SEED_M, CODIGO)
);

CREATE TABLE CRIATURA (
  ID NUMBER(3),
  NOME VARCHAR(30) NOT NULL,
  DESCRICAO VARCHAR(200),
  CONSTRAINT PK_CRIATURA PRIMARY KEY (ID)
);

CREATE TABLE DROPA (
  IDC NUMBER(3),
  IDI NUMBER(4),
  PROBABILIDADE NUMBER(3, 2),
  CONSTRAINT PK_DROPA PRIMARY KEY (IDC, IDI),
  CONSTRAINT FK_DROPA_IDC FOREIGN KEY (IDC) REFERENCES CRIATURA (ID),
  CONSTRAINT FK_DROPA_IDI FOREIGN KEY (IDI) REFERENCES ITEM (ID),
  CONSTRAINT CHK_PROBABILIDADE CHECK (PROBABILIDADE >= 0 AND PROBABILIDADE <= 1)
);

CREATE TABLE ANIMAL (
  IDC NUMBER(5), 
  DOMESTICAVEL BOOLEAN NOT NULL,
  CONSTRAINT PK_ANIMAL PRIMARY KEY (IDC),
  CONSTRAINT FK_ANIMAL_IDC FOREIGN KEY (IDC) REFERENCES CRIATURA(ID)
);

CREATE TABLE SERVO (
  IDC NUMBER(5),
  ATRIBUTO VARCHAR(15),
  CONSTRAINT PK_SERVO PRIMARY KEY (IDC),
  CONSTRAINT FK_SERVO_IDC FOREIGN KEY (IDC) REFERENCES CRIATURA(ID)
);

CREATE TABLE PROTEGE (
  IDCS NUMBER(5),
  SEEDMEF CHAR(50),
  CODIGOEF NUMBER(5),
  CONSTRAINT PK_PROTEGE PRIMARY KEY (IDCS, SEEDMEF, CODIGOEF),
  CONsTRAINT FK_PROTEGE_IDCS FOREIGN KEY (IDCS) REFERENCES SERVO (ID),
  CONSTRAINT FK_PROTEGE_SEEDMEF FOREIGN KEY (SEEDMEF, CODIGOEF) REFERENCES FORTALEZA (SEED_ME, CODIGO_E)
);

CREATE TABLE CHEFE (
  IDC NUMBER(5),
  SEEDMEF CHAR(50),
  CODIGOEF NUMBER(5),
  CONSTRAINT PK_CHEFE PRIMARY KEY (IDC),
  CONSTRAINT AK_CHEFE UNIQUE (SEEDMEF, CODIGOEF),
  CONSTRAINT FK_CHEFE_IDC FOREIGN KEY (IDC) REFERENCES CRIATURA (ID),
  CONSTRAINT FK_CHEFE_SEEDMEF FOREIGN KEY (SEEDMEF, CODIGOEF) REFERENCES FORTALEZA (SEED_ME, CODIGO_E)
);

CREATE TABLE ATRIBUTO (
  IDCC NUMBER(5),
  ATRIBUTO VARCHAR(15),
  CONSTRAINT PK_ATRIBUTO PRIMARY KEY (IDCC),
  CONSTRAINT FK_ATRIBUTO_IDCC FOREIGN KEY (IDCC) REFERENCES CHEFE (IDC)
);